### ISSUE TITLE
Make uglify-js a peerDependency

### ISSUE THREAD

**Issue by amilajack** [gdborton/webpack-parallel-uglify-plugin#27]
This will give users of the plugin a lot more control. This is also what the [webpack-contrib](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/package.json#L44-L46) plugin does. This makes using the [experimental es6 branch of uglifyjs possible](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#install):
```bash
yarn add git://github.com/mishoo/UglifyJS2#harmony-v2.8.22 --dev
```

**Comment by gdborton** [comment]
Support for `uglify-es` is planned, but will likely be added via a plugin option.  I'm not sure about making it a peerDependency as `uglify-es` has the same api as @3 and not @2 (this repo currently uses @2).  Installing one instead of the other may not work.

The current plan is to update this repo to `uglify-js@3` then add an option to the plugin to use `uglify-es` which will just change which uglifier is used at run time. This gives the benefit of finely controlling which of your assets are allowed to use es6 in their final output.

**Comment by amilajack** [comment]
Thanks for the clarification.
